version: '3'
services:
#  nginx_ssl:
#    image: nginx
#    restart: unless-stopped
#    hostname: nginx_ssl
#    ports:
#      - "443:443"
#    links:
#      - openvas
#    volumes:
#      - ./conf/nginx_rev.conf:/etc/nginx/conf.d/nginx.conf:ro
#      - ./data/nginx/ssl/:/ssl:ro
  openvas:
    restart: unless-stopped
    build:
      context: ./dockerfiles/.
    hostname: openvas11
    ports:
      - "443:443"
    volumes:
      - "./data/postgres/main:/var/lib/postgresql/12/main"
#      - "./data/signatures:/opt/var/lib/gvm/"
#    environment:
    # CHANGE THIS !
    #      - USERNAME:$OPENVAS_USERNAME
        #      - PASSWORD:$OPENVAS_PASSWORD
